### ISSUE TITLE
Feat: User Sign In with Email and Password

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/dynamites-ecomm-be#29]
## Description

As a registered user (vendor or buyer), I want to be able to sign in to the e-commerce platform using my email and password so that I can access my account and its respective features.

The sign-in process should securely authenticate the user's credentials and provide appropriate responses and error handling.

### Acceptance Criteria

- [x] Implement a user sign-in API endpoint
- [x] Validate user input (email and password)
- [x] Retrieve the user record from the database based on the provided email
- [x] Verify the provided password against the securely stored password hash
- [x] Generate and return an authentication token (e.g., JSON Web Token) upon successful sign-in
- [x] Return appropriate success or error responses
- [x] Implement input sanitization

## Developer Notes

- Define the API endpoint and request/response payloads
- Implement input validation and sanitization measures
- Retrieve user records securely from the database
- Use a secure password verification method (e.g., bcrypt, argon2)
- Generate and manage authentication tokens (e.g., JWT)
- Write unit tests to cover different scenarios and edge cases

## Related Issues

- #xx Add any issue that this depends on in the current sprint

## Definition of Done

- User sign-in API endpoint is implemented and functional
- User input validation and sanitization measures are in place
- User credentials are securely verified against stored data
- Authentication tokens are generated and returned upon successful sign-in
- Appropriate success and error responses are returned
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation is updated

**Comment by bertrandshema** [comment]
This PR has been Merged
