### ISSUE TITLE
Feat: Product Availability

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/dynamites-ecomm-be#38]
### Description

As a vendor, I should be able to mark a product as available or unavailable manually, so that buyers can view and purchase the available products. Products may need to be marked as unavailable due to reasons such as expiry date or out-of-stock situations.

### Acceptance Criteria

- [x] Implement an API endpoint for updating product availability
- [x] Validate the requesting user's role as a vendor
- [x] Validate the request payload (product ID, availability status)
- [x] Retrieve the product from the database based on the provided product ID
- [x] Ensure the product belongs to the requesting vendor
- [x] Update the product availability status in the database
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

### Developer Notes

- Document the API endpoint with Swagger
- Define the request payload structure for updating product availability
- Implement necessary validation checks for the request payload
- Update the product availability status in the database
- Handle scenarios where the product does not exist or does not belong to the requesting vendor
- Write unit tests to cover different scenarios and edge cases

### Related Issues

- #37 

### Definition of Done

- API endpoint for updating product availability is implemented and functional
- Validation checks are implemented for the requesting user's role and request payload
- Product availability status is updated in the database
- Appropriate error handling and response messages are implemented
- Input sanitization measures are in place
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation with Swagger is completed

**Comment by niyobern** [comment]
Deliverables at the end of the week:

Implement an API endpoint for updating product availability.
Handle authentication and authorization for vendors.
Ensure validation, error handling, and input sanitization.
Write unit tests, adhere to coding standards, and complete API documentation with Swagger.
Data Flow / Flowchart / Pseudocode / ERD Diagrams:

Create a flowchart illustrating the flow of data and operations within the product availability update operation.
Update the ERD diagram to visualize the database schema for storing product availability status.
Schedule of Implementation of Various Parts:

Day 1: Thursday (09/05/2024)
Set up the project environment with necessary dependencies by 08:00 PM.
Update the database schema for storing product availability status.
Day 2: Friday (10/05/2024)
Implement authentication mechanisms to validate vendor roles.
Design the API endpoint for product availability update and implement basic validation checks by 5:00 PM.
Day 3: Saturday (11/05/2024)
Complete integration of product availability update endpoint with authentication.
Implement error handling for validation failures and input sanitization by 5:00 PM.
Day 4: Sunday (12/05/2024)
Implement logic to handle product availability status in the database by 5:00 PM.
Day 5: Monday (13/05/2024)
Write unit tests for product availability update operation to ensure functionality.
Ensure adherence to coding standards and best practices.
Document API endpoint with Swagger and deploy to staging environment by 5:00 PM.
Additional Notes:

Conduct regular reviews and testing throughout the week to identify and address any issues promptly.
Collaborate closely with team members to ensure smooth integration of different components.
Maintain clear communication channels for feedback and updates on progress.
Allocate time for any unexpected challenges or additional requirements that may arise during implementation.
External services or libraries to be used:

Swagger for API documentation.
Jest for unit testing.
Express.js for API endpoint creation.
Mongoose for MongoDB object modeling.
Remember to replace the dates and other placeholders with the actual details of your implementation plan.

**Comment by niyobern** [comment]
### Deliverables at the end of the week:

- Implement an API endpoint for updating product availability.
- Handle authentication and authorization for vendors.
- Ensure validation, error handling, and input sanitization.
- Write unit tests, adhere to coding standards, and complete API documentation with Swagger.

### Data Flow / Flowchart / Pseudocode / ERD Diagrams:

**Flow Chat**

![product_availability drawio](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/85235653/681fc11d-f4ef-4f02-a85f-1cc12baff7dc)

**Database ERD**

![er drawio (1)](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/85235653/6a83daad-9c75-48e6-9afb-1d129c9716ab)


### Day 1: Thursday (09/05/2024)

- Set up the project environment with necessary dependencies by 08:00 PM.
- Update the database schema for storing product availability status.

### Day 2: Friday (10/05/2024)

- Implement authentication mechanisms to validate vendor roles.
- Design the API endpoint for product availability update and implement basic validation checks by 5:00 PM.

### Day 3: Saturday (11/05/2024)

- Complete integration of product availability update endpoint with authentication.
- Implement error handling for validation failures and input sanitization by 5:00 PM.

### Day 4: Sunday (12/05/2024)
Implement logic to handle product availability status in the database by 5:00 PM.
### Day 5: Monday (13/05/2024)

- Write unit tests for product availability update operation to ensure functionality.
- Ensure adherence to coding standards and best practices.
- Document API endpoint with Swagger and deploy to staging environment by 5:00 PM.

### Additional Notes:

- Conduct regular reviews and testing throughout the week to identify and address any issues promptly.
- Collaborate closely with team members to ensure smooth integration of different components.
- Maintain clear communication channels for feedback and updates on progress.
- Allocate time for any unexpected challenges or additional requirements that may arise during implementation.

### External services or libraries to be used:

- Swagger for API documentation.
- Jest for unit testing.
- Express.js for API endpoint creation.
