### ISSUE TITLE
Feat: Buyer should be able to search a product

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/dynamites-ecomm-be#56]
---
### Description

Buyers can easily find what they're looking for using our search tool. Just type keywords or use filters like category, brand ,product name  help user  to discover products and to saving time .

### Acceptance Criteria

- Make search functions
- provide endpoint for search functions
-  Validate user input to prevent invalid or malicious search queries, ensuring security and data integrity.
- Implement error handling mechanisms to gracefully manage any unexpected errors or failures during 
  the search process.
- Unit test on search
- write swagger document  for search endpoint

### Related Issues

- #38
- #37

### Definition of Done

- Endpoint of  search functions (Buyer can search a product)
- Unit test for search which passing
- Complete swagger document  for search endpoint

**Comment by Dawaic6** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-9a2217fd-7fff-a8f5-86e9-2e9e6a8fd410"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#1. Deliverables at the end of the project.</span></h2><p dir="ltr" style="line-height:1.7999999999999998;margin-left: 36pt;margin-right: -11pt;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><br /></p><div dir="ltr" style="margin-left:0pt;" align="left">
- Endpoint of  search functions (Buyer can search a product)- Unit test for search which passing- Complete swagger document  for search endpoint
--


</div><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#2. Data flow / Flowchart / pseudocode / ERD diagrams</span></h2><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:285px;"><img src="https://lh7-us.googleusercontent.com/l0_utHSlODoQxdFB_HVLfYrVdLj8Wx5oNOv1X626llbXXRV6TTypqsxdzRXuTXpT3TtpLO06AqsHYW32kgJrghyRWvHmvsLAtkF6boyRGvL27yDrQBcyE5ZiYzKafOCEXy_NG0f7wrBNRscERIxbyRA" width="624" height="285" style="margin-left:0px;margin-top:0px;" /></span></span></p><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#3. Schedule of implementation of the various parts</span></h2><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"># Thursday (16th/May/2024)</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;Endpoint of&nbsp; search functions (Buyer can search a product)</span></p></li></ul><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#Friday (17th/May/2024)</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:10.5pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;Unit test for search which passing</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:10.5pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Complete swagger document&nbsp; for search endpoint&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.7999999999999998;margin-left: 36pt;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><br /></p><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#4. Dependencies/Foreseen blockers from team members</span></h2><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;#37</span></p></li></ul><br /><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#38</span></p></li></ul></b>
</body>
</html>
